// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"gorm.io/gorm"
	"task/api/handler"
	"task/internal/repository"
	"task/internal/service"
)

// Injectors from wire.go:

// InitTaskHandler 初始化TaskHandler
func InitTaskHandler(db *gorm.DB) (*handler.TaskHandler, error) {
	taskRepository := repository.NewTaskRepository(db)
	taskService := service.NewTaskService(taskRepository)
	taskHandler := handler.NewTaskHandler(taskService)
	return taskHandler, nil
}

// wire.go:

// ProviderSet 定义provider的集合
var taskProviderSet = wire.NewSet(repository.NewTaskRepository, service.NewTaskService, handler.NewTaskHandler)
